AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  UseCache: false
  Exclude:
    - vendor/**/*

LineLength:
  Max: 120

ClassLength:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

HashSyntax:
   EnforcedStyle: ruby19

Style/SignalException:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics:
  Enabled: false

Style/WordArray:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false

# %w[] shows that it will return an array
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

# for single `/` more readable
Style/RegexpLiteral:
  Enabled: false

# sometimes the most readable way of doing things
Style/ClassVars:
  Enabled: false

# nice for .with{} mock stubs
Style/Semicolon:
  Enabled: false

# for simple cases more readable
Style/GuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: false
