language: bash
services:
- docker
branches:
  only: master
before_script:
- docker -v
- docker build -t secret_tester .
script: docker run -it --rm secret_tester rake $TASK
env:
- TASK=test
- TASK=rubocop
