steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/apps/samson_secret_puller:$SHORT_SHA'
      - "--label=revision=$COMMIT_SHA"
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/apps/samson_secret_puller:$SHORT_SHA'
