#FROM ruby:2.6.2-alpine
FROM ruby@sha256:9fee6680610546f3f50e3d00e63ca73b53f6bc04a2b0ed4cd70b126956358e4e

RUN apk add --update --no-cache bash curl openssl elixir erlang-crypto

WORKDIR /app

# bundle
COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle install --quiet --jobs 4

# code
COPY bin /app/bin
COPY lib /app/lib

# test
COPY Rakefile .travis.yml .rubocop.yml ./
COPY test /app/test

# clients
COPY gem gem
COPY elixir elixir
RUN mix local.hex --force

CMD ["bash"]
