FROM ruby:2.6-alpine

RUN apk add --update --no-cache bash curl openssl elixir erlang-crypto

WORKDIR /app

# bundle
COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle install --quiet --jobs 4

# code
COPY bin /app/bin
COPY lib /app/lib

# test
COPY Rakefile .travis.yml .rubocop.yml ./
COPY test /app/test

# clients
COPY gem gem
COPY elixir elixir
RUN mix local.hex --force

CMD ["bash"]
