# FROM ruby:2.6.3-alpine
FROM ruby@sha256:2749716577d81ef71bc487dfd35962bb067ca11a1b9d6d6d81f8ff7cc3e03f60

RUN apk add --update --no-cache bash curl openssl elixir erlang-crypto build-base

WORKDIR /app

# bundle
COPY .ruby-version Gemfile Gemfile.lock ./
RUN bundle install --quiet --jobs 4

# code
COPY bin /app/bin
COPY lib /app/lib

# test
COPY Rakefile .travis.yml .rubocop.yml ./
COPY test /app/test

# clients
COPY gem gem
COPY elixir elixir
RUN mix local.hex --force

CMD ["bash"]
