apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: truth-service
  labels:
    project: truth-service
    role: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      project: truth-service
      role: primary
  template:
    metadata:
      name: truth-service-pod
      labels:
        project: truth-service
        role: primary
    spec:
      volumes:
      - name: secrets-volume
        emptyDir: {}
      - name: vaultauth
        secret:
          secretName: "vaultauth"
      containers:
      - image: docker-registry.zende.sk/truth_service:truth_with_secrets_v3
        name: primary-container
        ports:
        - name: primary-port
          containerPort: 4242
          protocol: TCP
        volumeMounts:
        - mountPath: /secrets
          name: secrets-volume
      - image: docker-registry.zende.sk/truth_service:secrets_sidecar_v8
        name: sidecar-container
        volumeMounts:
        - mountPath: /secrets
          name: secrets-volume
        - mountPath: /vault-auth
          name: vaultauth
---
apiVersion: v1
kind: Service
metadata:
  name: truth-service
  labels:
    project: truth-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: primary-port
  selector:
    project: truth-service
    role: primary
