require 'bundler/setup'
require 'bundler/gem_tasks'
require 'bump/tasks'

# make `rake release` not tag the repo since this repo includes multiple components
push = "release:source_control_push"
Rake::Task[push].clear
task "release:source_control_push" do
  sh "git", "push"
end
