# frozen_string_literal: true

require_relative "lib/version"

name = "samson_secret_puller"

Gem::Specification.new name, SamsonSecretPuller::VERSION do |s|
  s.summary = "Gem to read secrets generated by samson secret puller"
  s.authors = ["Michael Grosser"]
  s.email = "michael@grosser.it"
  s.homepage = "https://github.com/zendesk/#{name}"
  s.files = Dir.glob("lib/**/*") + ['Readme.md', 'MIT-LICENSE.txt']
  s.license = "MIT"
  s.required_ruby_version = '>= 2.7'
end
