name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build .
    - run: docker build -t secret_tester -f Dockerfile.dev .
    - run: docker run --rm secret_tester bundle exec rake test
    - run: docker run --rm secret_tester bundle exec rake rubocop
