name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: zendesk/checkout@v2
    - run: docker build .
    - run: docker build -t secret_tester -f Dockerfile.dev .
    - run: docker run --rm secret_tester bundle exec rake test
    - run: docker run --rm secret_tester bundle exec rake rubocop
